apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
  namespace: default
data:
{{- if .Values.hazelcast.configurationFiles }}
{{- range $key, $val := .Values.hazelcast.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end -}}
{{- else }}
  hazelcast.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.10.xsd"
                   xmlns="http://www.hazelcast.com/schema/config"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

      <properties>
        <property name="hazelcast.discovery.enabled">true</property>
      </properties>
      <network>
        <join>
          <multicast enabled="false"/>
          <tcp-ip enabled="false" />
          <discovery-strategies>
            <discovery-strategy enabled="true" class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
            </discovery-strategy>
          </discovery-strategies>
        </join>
      </network>
      <hot-restart-persistence enabled="{{ .Values.hazelcast.hotRestart.enabled }}">
          <base-dir>/data/persistent/${podName}</base-dir>
          <parallelism>{{ .Values.hazelcast.hotRestart.parallelism }}</parallelism>
          <validation-timeout-seconds>{{ .Values.hazelcast.hotRestart.validationTimeoutSeconds }}</validation-timeout-seconds>
          <data-load-timeout-seconds>{{ .Values.hazelcast.hotRestart.dataLoadTimeoutSeconds }}</data-load-timeout-seconds>
          <cluster-data-recovery-policy>{{ .Values.hazelcast.hotRestart.clusterDataRecoveryPolicy }}</cluster-data-recovery-policy>
      </hot-restart-persistence>
      <map name="test-map">
          <hot-restart enabled="true">
            <fsync>true</fsync>
          </hot-restart>
      </map>
    </hazelcast>
  {{- end }}
